### ISSUE TITLE
DTS - Superb by the way - New script if possible please.

### ISSUE THREAD

**Issue by paulhew69** [doryosef/dts#1]
Hi.
I have been wanting to create timelapses on my printer, but since moving to Duet3D boards it has been a hard struggle, until I found your post on the Duet3D forum. I have tried the rest but could not get them to work.

In a nutshell your solution is brilliant. I have posted on the Duet forum as I would like to write a guide on how to install and use it as I know there are others who would benefit from it too.
I am NOT a coder! 
I have been trying to modify the Final step to run on the Pi so it creates the final file on the Pi and you do not have to run anything else on another platform.

Is there any chance you could write a different script so the final encoding is done on the Pi, then copies the movie to a user specified folder?

In my guide I will also show them how to install FFMPEG and Samba so they can easily retrieve their files.

Hope you can help.

Thank you for your time and brilliant solution.

Regards,
Paul

**Comment by doryosef** [comment]
Hi Paul,
Thanks for reaching out, It's nice to see my solution can benefit others

*Is there any chance you could write a different script so the final
encoding is done on the Pi, then copies the movie to a user specified
folder?*

For this project I used raspberry pi zero which don't have the CPU power to
use ffmpeg I think even pi 4 will not handle this kind of job properly BUT
If you do want to execute the ffmpeg on your pi or any other command it's
pretty easy.
all you need to is install ffmpeg, add script under "
*/opt/dts/scripts/<YOUR_SCRIPT>*", which execute ffmpeg and add it to *conf.ini
*under commands

Hope it help

‫בתאריך יום ג׳, 25 בפבר׳ 2020 ב-23:01 מאת ‪paulhew69‬‏ <‪
notifications@github.com‬‏>:‬
